#pragma once
#include <opencv2/objdetect/objdetect.hpp>
#include <opencv2/highgui/highgui.hpp>
#include <opencv2/imgproc/imgproc.hpp>
#include <opencv2/core/core.hpp>
#include <opencv2/features2d.hpp>
#include <iostream>
#include <stdio.h>
#include <stdlib.h>
#include <map>
#include <math.h>
using namespace cv;
using namespace std;

/**
* Pipeline class.
* 
* Autogenerated Pipeline from GRIP
*
* Make sure to set sources before running process()
*/
class Pipeline {
	private:
		Mat source0;
		Mat rgbThresholdOutput;
		vector<vector<cv::Point> > findContoursOutput;
		void rgbThreshold(Mat &, double [], double [], double [], Mat &);
		void findContours(Mat &, bool , vector<vector<cv::Point> > &);

	public:
		Pipeline();
		void Process();
		void setsource0(Mat &source0);
		Mat* getrgbThresholdOutput();
		vector<vector<cv::Point> >* getfindContoursOutput();
};

